version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /ExtractSampleSVEvidence.wdl
    testParameterFiles:
      - /test_input.wdl.json
    authors:
      - name: Justin Lim
        email: jlim21@mgh.harvard.edu
    topic: Split batch PE, SR, RD, and BAF evidence into sample evidence
